"""empty message

Revision ID: 40cba13fd502
Revises: 5607561dbe12
Create Date: 2014-05-19 10:39:58.078492

"""

# revision identifiers, used by Alembic.
revision = '40cba13fd502'
down_revision = '5607561dbe12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('melons', sa.Column('flesh_color', sa.String(length=30), nullable=True))
    op.add_column('melons', sa.Column('rind_color', sa.String(length=30), nullable=True))
    op.add_column('melons', sa.Column('seedless', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivered_at')
    op.drop_column('melons', 'seedless')
    op.drop_column('melons', 'rind_color')
    op.drop_column('melons', 'flesh_color')
    ### end Alembic commands ###
