"""empty message

Revision ID: 5607561dbe12
Revises: None
Create Date: 2014-05-15 14:31:13.743826

"""

# revision identifiers, used by Alembic.
revision = '5607561dbe12'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salespeople',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('givenname', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salespeople_email'), 'salespeople', ['email'], unique=True)

    op.create_table('melons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('melon_type', sa.String(length=30), nullable=True),
    sa.Column('common_name', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('imgurl', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('givenname', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('tos_agree', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('Not Specified', 'Male', 'Female', 'Other'), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('billto_address1', sa.String(length=40), nullable=True),
    sa.Column('billto_address2', sa.String(length=40), nullable=True),
    sa.Column('billto_city', sa.String(length=35), nullable=True),
    sa.Column('billto_state', sa.String(length=35), nullable=True),
    sa.Column('billto_postalcode', sa.String(length=10), nullable=True),
    sa.Column('shipto_address1', sa.String(length=40), nullable=True),
    sa.Column('shipto_address2', sa.String(length=40), nullable=True),
    sa.Column('shipto_city', sa.String(length=35), nullable=True),
    sa.Column('shipto_state', sa.String(length=35), nullable=True),
    sa.Column('shipto_postalcode', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('New', 'Processing', 'Out for Delivery', 'Delivered', 'Canceled'), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('salesperson_id', sa.Integer(), nullable=True),
    sa.Column('shipto_address1', sa.String(length=40), nullable=True),
    sa.Column('shipto_address2', sa.String(length=40), nullable=True),
    sa.Column('shipto_city', sa.String(length=35), nullable=True),
    sa.Column('shipto_state', sa.String(length=35), nullable=True),
    sa.Column('shipto_postalcode', sa.String(length=10), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=True),
    sa.Column('delivery_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_salesperson_id'), 'orders', ['salesperson_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('melon_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_order_items_melon_id'), 'order_items', ['melon_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_melon_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_salesperson_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('melons')
    op.drop_index(op.f('ix_salespeople_email'), table_name='salespeople')
    op.drop_table('salespeople')
    ### end Alembic commands ###
